services:
  bentobox:
    image: bentobox:latest # Replace with the correct image if needed
    container_name: bentobox_container
    environment:
      PGHOST: db
      PGUSER: devuser
      PGPASSWORD: devpassword
      PGDATABASE: bentobox
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    networks:
      - bentobox_network

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: bentobox
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bentobox_network

volumes:
  postgres_data:

networks:
  bentobox_network:
    driver: bridge
